services:
  postgres:
    image: postgres:15
    container_name: aviation-postgres
    restart: always
    environment:
      POSTGRES_DB: aviation_db
      POSTGRES_USER: aviation_user
      POSTGRES_PASSWORD: aviation_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth_service
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - postgres
  aircraft-service:
    build:
      context: .
      dockerfile: apps/aircraft-service/Dockerfile
    container_name: aircraft_service
    env_file:
      - .env
    ports:
      - "3002:3002"
    restart: unless-stopped
    depends_on:
      - postgres
  flight-service:
    build:
      context: .
      dockerfile: apps/flight-service/Dockerfile
    container_name: flight_service
    env_file:
      - .env
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - postgres
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: aviation_frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - auth-service
      - aircraft-service
      - flight-service

volumes:
  postgres_data:
